# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5b7e8fc4b14ca23af7fb2c0c296d0b8fbe0400a4c072c37de8cc8f3a886b255c9251f9e865eedcb06b7da6138f59c7996cf3faa95658d6bf8f1500249d0145

test:
  secret_key_base: 891cf000555afad2b2f427e6bcde8265138074e24e2eee530430af418cc07104ffc2c09109fa5d16bd7b6604a26df7213dfbc154f172d4efdd4fa0139702056f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
